# Generated by Django 3.0.5 on 2023-01-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_auto_20230113_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='nom',
            field=models.CharField(choices=[('Cardiologue', 'Cardiologie'), ('Dermatologue', 'Dermatologie'), ('Urgentiste', 'Urgence'), ('Allergiste/Immunologiste', 'Allergie/Immunologie'), ('Anesthesiste', 'Chirurgie'), ('Biologiste', 'Biologie'), ('Radiologue', 'Radiologie'), ('Ophtalmologue', 'Ophtalmologie'), ('Dentiste', 'Odontologie'), ('Pharmacien', 'Pharmacie'), ('Généraliste', 'Consultation'), ('Chimiste', 'Laboratoire'), ('Chirurgien', 'Reanimation')], default='Consultation', max_length=50),
        ),
    ]
