# Generated by Django 3.0.5 on 2023-01-14 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_auto_20230113_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='symptoms',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
