# Generated by Django 3.0.5 on 2023-01-14 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0007_auto_20230114_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='docteur',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='secretaire',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
