# Generated by Django 3.0.5 on 2023-01-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0008_auto_20230114_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='motif',
            field=models.CharField(default='Aucun motif particulier', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='priorite',
            field=models.CharField(choices=[('Urgent', 'Urgent'), ('Moyen', 'Moyen'), ('Faible', 'Faible')], default='Moyen', max_length=7),
        ),
    ]
