# Generated by Django 3.0.5 on 2023-01-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0012_auto_20230114_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='admission',
            field=models.DateTimeField(null=True),
        ),
    ]
