# Generated by Django 3.0.5 on 2023-01-15 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0014_auto_20230115_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendezvous',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
