# Generated by Django 3.0.5 on 2023-01-17 14:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0015_auto_20230115_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendezvous',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='heure',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
    ]
